language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install nose
- pip install coveralls
script:
- python setup.py install
- nosetests -vdx tests/ --with-coverage --cover-package=oct
after_success:
  - coverage combine
  - coveralls
